#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: OpenWrt-CI

on:
   push:
     branches: 
       - master
   schedule:
    - cron: 0 16 * * 3
  # release:
  #   types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          # 利用挂载在 /mnt/ 的 14G 额外空间:
          # sudo mkdir -p -m 777 /mnt/openwrt/bin /mnt/openwrt/build_dir/host /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir
          # ln -s /mnt/openwrt/bin ./bin
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/host ./build_dir/host
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/hostpkg ./build_dir/hostpkg
          # ln -s /mnt/openwrt/dl ./dl
          # ln -s /mnt/openwrt/feeds ./feeds
          # ln -s /mnt/openwrt/staging_dir ./staging_dir
          df -h
      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Generate configuration file
        run: |
          rm -f ./.config*
          touch ./.config

          cat >> .config <<EOF

          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y
          CONFIG_TARGET_x86_64_Generic=y
          # CONFIG_GRUB_IMAGES is not set
          CONFIG_PACKAGE_adblock=m
          # CONFIG_PACKAGE_autosamba is not set
          CONFIG_PACKAGE_bash=y
          CONFIG_PACKAGE_dejavu-fonts-ttf-DejaVuMathTeXGyre=y
          CONFIG_PACKAGE_dejavu-fonts-ttf-DejaVuSans=y
          CONFIG_PACKAGE_dejavu-fonts-ttf-DejaVuSansCondensed=y
          CONFIG_PACKAGE_dejavu-fonts-ttf-DejaVuSansMono=y
          CONFIG_PACKAGE_dejavu-fonts-ttf-DejaVuSerif=y
          CONFIG_PACKAGE_dejavu-fonts-ttf-DejaVuSerifCondensed=y
          # CONFIG_PACKAGE_grub2 is not set
          CONFIG_PACKAGE_gzip=y
          CONFIG_PACKAGE_kcptun-client=y
          # CONFIG_PACKAGE_kmod-nf-conntrack-netlink is not set
          CONFIG_PACKAGE_kmod-sched-connmark=m
          CONFIG_PACKAGE_libbz2=m
          CONFIG_PACKAGE_libcap=y
          CONFIG_PACKAGE_libexif=m
          CONFIG_PACKAGE_libffmpeg-audio-dec=m
          CONFIG_PACKAGE_libflac=m
          CONFIG_PACKAGE_libid3tag=m
          CONFIG_PACKAGE_libjpeg=m
          CONFIG_PACKAGE_libogg=m
          CONFIG_PACKAGE_libsqlite3=m
          CONFIG_PACKAGE_libvorbis=m
          CONFIG_PACKAGE_luci-app-adblock=m
          CONFIG_PACKAGE_luci-app-minidlna=m
          # CONFIG_PACKAGE_luci-app-nlbwmon is not set
          CONFIG_PACKAGE_luci-app-qos=m
          CONFIG_PACKAGE_luci-app-samba=m
          CONFIG_PACKAGE_luci-app-simple-adblock=m
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Kcptun=y
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Socks=y
          # CONFIG_PACKAGE_luci-app-xlnetacc is not set
          CONFIG_PACKAGE_luci-i18n-adblock-zh-cn=m
          CONFIG_PACKAGE_luci-i18n-minidlna-zh-cn=m
          CONFIG_PACKAGE_luci-i18n-qos-zh-cn=m
          CONFIG_PACKAGE_luci-i18n-samba-zh-cn=m
          CONFIG_PACKAGE_luci-theme-material=y
          CONFIG_PACKAGE_minidlna=m
          # CONFIG_PACKAGE_nlbwmon is not set
          CONFIG_PACKAGE_ntpclient=y
          CONFIG_PACKAGE_qos-scripts=m
          CONFIG_PACKAGE_samba36-server=m
          CONFIG_PACKAGE_simple-adblock=m
          CONFIG_PACKAGE_srelay=y
          CONFIG_PACKAGE_vim-fuller=y
          # CONFIG_PACKAGE_wsdd2 is not set
          CONFIG_PACKAGE_zsh=y
          CONFIG_SQLITE_FTS3=y
          CONFIG_SQLITE_RTREE=y
          # CONFIG_TARGET_IMAGES_PAD is not set
          # CONFIG_TARGET_ROOTFS_SQUASHFS is not set

          EOF

          sed -i 's/^[ \t]*//g' ./.config
          make defconfig
      - name: Make download
        run: |
          make download -j8
          find dl -size -1024c -exec rm -f {} \;
      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin
      - name: Prepare artifact
        run: find ./bin/targets/ -type d -name "packages" | xargs rm -rf {}

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt firmware
          path: ./bin/targets/
